struct Nutrition: Codable, Equatable {
    let alcohol_100g: Double?
    let calcium_100g: Double?
    let calories_100g: Double?
    let carbs_100g: Double?
    let chloride_100g: Double?
    let cholesterol_100g: Double?
    let copper_100g: Double?
    let fat_100g: Double?
    let fibers_100g: Double?
    let glycemic_index: Double?
    let insat_fat_100g: Double?
    let iodine_100g: Double?
    let iron_100g: Double?
    let magnesium_100g: Double?
    let manganese_100g: Double?
    let mono_fat_100g: Double?
    let omega_3_100g: Double?
    let omega_6_100g: Double?
    let phosphorus_100g: Double?
    let poly_fat_100g: Double?
    let polyols_100g: Double?
    let potassium_100g: Double?
    let proteins_100g: Double?
    let salt_100g: Double?
    let sat_fat_100g: Double?
    let selenium_100g: Double?
    let sodium_100g: Double?
    let sugars_100g: Double?
    let veg_percent: Double?
    let vitamin_a_beta_k_100g: Double?
    let vitamin_a_retinol_100g: Double?
    let vitamin_b12_100g: Double?
    let vitamin_b1_100g: Double?
    let vitamin_b2_100g: Double?
    let vitamin_b3_100g: Double?
    let vitamin_b5_100g: Double?
    let vitamin_b6_100g: Double?
    let vitamin_b9_100g: Double?
    let vitamin_c_100g: Double?
    let vitamin_d_100g: Double?
    let vitamin_e_100g: Double?
    let vitamin_k1_100g: Double?
    let water_100g: Double?
    let zinc_100g: Double?
}
